testing automerge

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -59,41 +59,41 @@ jobs:
   auto-merge:  
     runs-on: ubuntu-latest
     needs: auto-approve
-    # steps:
-    #   - id: automerge
-    #     name: automerge
-    #     uses: pascalgn/automerge-action@v0.15.6
-    #     env:
-    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    #       MERGE_FILTER_AUTHOR: 'cloudlovely'
-    #       MERGE_METHOD: "merge"
-    #       MERGE_DELETE_BRANCH: "true"
-    #       MERGE_LABELS: "automerge"
-    #       MERGE_REQUIRED_APPROVALS: "0"
     steps:
-      - name: Check if all status checks are successful
-        id: check-status
-        run: |
-          PR_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/status)
-
-          if echo "$PR_STATUS" | jq -e '.statuses[] | select(.state != "success" and .context != "automerge")' > /dev/null; then
-            echo "At least one check failed or pending, aborting merge."
-            exit 1
-          fi
+      - id: automerge
+        name: automerge
+        uses: pascalgn/automerge-action@v0.15.6
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
-
-      - name: Automerge if checks pass
-        if: steps.check-status.run.result == 'success'
-        uses: "pascalgn/automerge-action@v0.15.6"
-        env:
-          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" 
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           MERGE_FILTER_AUTHOR: 'cloudlovely'
           MERGE_METHOD: "merge"
           MERGE_DELETE_BRANCH: "true"
           MERGE_LABELS: "automerge"
           MERGE_REQUIRED_APPROVALS: "1"
+    # steps:
+    #   - name: Check if all status checks are successful
+    #     id: check-status
+    #     run: |
+    #       PR_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+    #       -H "Accept: application/vnd.github.v3+json" \
+    #       https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/status)
+
+    #       if echo "$PR_STATUS" | jq -e '.statuses[] | select(.state != "success" and .context != "automerge")' > /dev/null; then
+    #         echo "At least one check failed or pending, aborting merge."
+    #         exit 1
+    #       fi
+    #     env:
+    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+
+    #   - name: Automerge if checks pass
+    #     if: steps.check-status.run.result == 'success'
+    #     uses: "pascalgn/automerge-action@v0.15.6"
+    #     env:
+    #       GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" 
+    #       MERGE_FILTER_AUTHOR: 'cloudlovely'
+    #       MERGE_METHOD: "merge"
+    #       MERGE_DELETE_BRANCH: "true"
+    #       MERGE_LABELS: "automerge"
+    #       MERGE_REQUIRED_APPROVALS: "1"
 
 
